### ISSUE TITLE
Why does ws2812-2020 work?

### ISSUE THREAD

**Issue by xyzz** [sparkfun/SparkFun_Pro_Micro-RP2040#3]
The status LED ws2812 is directly connected to RAW on vdd and directly to rp2040 gpio on data input:

![image](https://user-images.githubusercontent.com/1065521/132087027-a8e1df63-b25b-4c60-8ed5-e0d6276a569b.png)

From the datasheet for ws2812-2020, input voltage high is 0.7*vdd min

![image](https://user-images.githubusercontent.com/1065521/132087069-5f96d503-4d3c-48ae-8bd4-36d9d466ef1b.png)

i.e. 0.7 * 5v = 3.5v, this is higher than rp2040 3.3v io voltage

Assuming 0.3v drop on the diode here:

![image](https://user-images.githubusercontent.com/1065521/132087116-6e9b01c8-ae02-4748-8b29-893384307163.png)

it is now 0.7 * (5 - 0.3) = 3.29v, barely within 3.3v.

<hr>

So then how does that work, is there a mistake with my understanding? And is it reliable with the current implementation?

**Comment by nseidle** [comment]
This is a [known trick](https://todbot.com/blog/2017/01/12/crashspace-bigbutton-w-esp8266/), albeit pushing-the-spec wiring of the WS2812. The internet is ripe with posts from users who had very good success driving 5V LED strips from 3.3V logic.

Is it reliable? Yes for our implementation and LED vendor. But I would be cautious implementing a larger scale product without first vetting your specific design+supplier. 

Sorry, I hope that not-answer answers your question :)
