### ISSUE TITLE
Values for C11 / C13 too low?

### ISSUE THREAD

**Issue by sol** [sparkfun/SparkFun_Pro_Micro-RP2040#4]
Hi there 👋

I was looking at the schematics and noticed that the values for C11 / C13 are somewhat low.

I don’t have a background in electrical engineering, so I may very well miss something obvious.

![4742BB73-90ED-44D4-9399-096BE0A5CE9A](https://user-images.githubusercontent.com/461132/171034289-cac1b54a-f470-477b-a381-176308d092ef.jpeg)

The schematic uses a 18pF crystal together with 2 x 15pF capacitors. Does this match the parts that you use for production? Is the actual BOM available somewhere?

**Comment by nseidle** [comment]
Hmm, I think they should be lower.

RPi writes this up in [their docs](https://datasheets.raspberrypi.com/rp2040/hardware-design-with-rp2040.pdf) (see the Crystal section).

My design notes from 2 years ago: "A 12MHz crystal with 8pF load was chosen and sourced (part #: ECS-120-8-36B-CWY-TR). The 15pF load caps should load this with 7.5pF."

I didn't show my math (bad engineer!) so I'm not sure how I ended up with 15pF; I think it's wrong. Crystal [datasheet](https://ecsxtal.com/store/pdf/ECX-2236B.pdf). CL is 8pF so it follows that with Cstray of around 3pF, the load caps should be around 10pF. The 15pF caps themselves have 5% tolerance. In retrospect, a 10pF cap would possibly be a better load.

While I can't explain my math, I'm not too concerned. We need to hit USB spec tolerances to be able to communicate successfully and we do.
